#!/bin/bash

if [ -z "$COPILOTUP_HOME_DIR" ]; then
    echo "please set COPILOTUP_HOME_DIR" >&2
    exit 1
fi

if [ "$#" -ne 1 ]; then
    echo "expected just a project path" >&2
    exit 1
fi

if command -v podman >/dev/null 2>&1; then
    CONTAINER_RUNTIME=podman
elif command -v docker >/dev/null 2>&1; then
    CONTAINER_RUNTIME=docker
else
    echo "container runtime not found. please install podman or docker." >&2
    exit 1
fi

if [ "$1" = "--container-runtime" ]; then
    echo "$CONTAINER_RUNTIME"
    exit 0
fi

COPILOTUP_HOME_DIR_PATH="$(realpath "$COPILOTUP_HOME_DIR")"
PROJECT_PATH="$(realpath $1)"
PROJECT_NAME="$(basename "$PROJECT_PATH")"

exec "$CONTAINER_RUNTIME" run --rm -ti \
    -v "$COPILOTUP_HOME_DIR_PATH:/root:rw" \
    -v "$PROJECT_PATH:/root/$PROJECT_NAME:rw" \
    -w "/root/$PROJECT_NAME" \
    copilotup
